export { default as Home } from "./Home";
export { default as LandingPage } from "./LandingPage";
export { default as Match } from "./Match";
export { default as Matches } from "./Matches";
export { default as Profile } from "./Profile";
export { default as EditProfile } from './EditProfile';
export { default as Leaderboard } from './Leaderboard';
export { default as Blocks} from './Blocks';
export { default as Mutes} from './Mutes';
export { default as BetHistory} from './BetHistory';